"use client";

import { useState } from "react";
import { Activity, ArrowUpRight, BarChart3, Bell, Boxes, CalendarDays, ChevronRight, CircleDot, CreditCard, ExternalLink, GitBranch, LayoutDashboard, Menu, Network, Package, Plus, Settings, ShieldCheck, Sparkles, X, Zap } from "lucide-react";

const products = [
  { id:"finance", name:"Finance Flow AI", category:"Financeiro", status:"active", description:"Finanças, CRM, agenda, relatórios e operações.", url:"https://financialtp.vercel.app", icon:CreditCard, metric:"Produto ativo", accent:"from-emerald-400/20 to-cyan-400/5" },
  { id:"agenda", name:"Agenda Flow", category:"Operações", status:"planned", description:"Agenda e gestão operacional independente.", url:"#", icon:CalendarDays, metric:"Planeado", accent:"from-violet-400/20 to-blue-400/5" },
  { id:"marketing", name:"Marketing Flow", category:"Marketing", status:"planned", description:"Campanhas, leads, conteúdo e aquisição.", url:"#", icon:Zap, metric:"Planeado", accent:"from-amber-400/20 to-orange-400/5" },
  { id:"ai", name:"AI Flow", category:"Inteligência", status:"planned", description:"Agentes e automações inteligentes para o ecossistema.", url:"#", icon:Sparkles, metric:"Planeado", accent:"from-fuchsia-400/20 to-purple-400/5" },
];

const nav = [
  ["overview","Visão geral",LayoutDashboard], ["products","Produtos",Boxes], ["ecosystem","Ecossistema",Network], ["activity","Atividade",Activity], ["settings","Definições",Settings]
] as const;

export default function Home() {
  const [active, setActive] = useState("overview");
  const [mobile, setMobile] = useState(false);
  const [windowProduct, setWindowProduct] = useState<typeof products[number] | null>(null);

  return <div className="min-h-screen grid-bg">
    <aside className={`fixed z-40 inset-y-0 left-0 w-64 glass border-y-0 border-l-0 p-5 flex flex-col transition-transform lg:translate-x-0 ${mobile ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex items-center justify-between mb-10"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-white to-zinc-400 text-black flex items-center justify-center font-black">E</div><div><div className="font-bold tracking-tight">Ecosystem OS</div><div className="text-[11px] text-zinc-500">Business operating system</div></div></div><button className="lg:hidden" onClick={()=>setMobile(false)}><X size={18}/></button></div>
      <div className="text-[10px] uppercase tracking-[.2em] text-zinc-600 mb-3">Control center</div>
      <nav className="space-y-1">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setActive(id);setMobile(false)}} className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm transition ${active===id?"bg-white text-black":"text-zinc-400 hover:text-white hover:bg-white/5"}`}><Icon size={17}/>{label}{id==="products"&&<span className="ml-auto text-[10px] bg-white/10 px-1.5 py-0.5 rounded">4</span>}</button>)}</nav>
      <div className="mt-auto glass rounded-2xl p-4"><div className="flex items-center gap-2 text-xs text-zinc-400"><ShieldCheck size={15} className="text-emerald-400"/> Sistema protegido</div><div className="mt-3 text-xs text-zinc-600">Admin workspace</div></div>
    </aside>

    <main className="lg:ml-64 min-h-screen">
      <header className="h-20 px-5 lg:px-8 flex items-center justify-between border-b border-white/5 bg-[#07090d]/80 backdrop-blur-xl sticky top-0 z-30"><div className="flex items-center gap-3"><button className="lg:hidden p-2 rounded-lg bg-white/5" onClick={()=>setMobile(true)}><Menu size={19}/></button><div><div className="text-xs text-zinc-500">Workspace / Admin</div><h1 className="font-semibold">{nav.find(n=>n[0]===active)?.[1]}</h1></div></div><div className="flex items-center gap-2"><button className="p-2.5 rounded-xl bg-white/5 hover:bg-white/10"><Bell size={17}/></button><div className="w-9 h-9 rounded-xl bg-zinc-800 border border-white/10 flex items-center justify-center text-xs font-bold">LK</div></div></header>

      <div className="p-5 lg:p-8 max-w-[1500px] mx-auto">
        {active==="overview" && <>
          <section className="relative overflow-hidden rounded-3xl border border-white/10 p-7 lg:p-10 bg-gradient-to-br from-zinc-900 via-zinc-950 to-black"><div className="absolute -top-28 -right-20 w-96 h-96 rounded-full bg-white/5 blur-3xl"/><div className="relative max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-[11px] text-zinc-300"><CircleDot size={11} className="text-emerald-400"/> Ecosystem online</div><h2 className="mt-5 text-3xl lg:text-5xl font-semibold tracking-tight">A raiz de todos os teus negócios.</h2><p className="mt-4 text-zinc-400 max-w-2xl leading-7">Um único centro para visualizar, abrir e futuramente conectar todos os produtos do teu ecossistema empresarial.</p><div className="mt-7 flex gap-3"><button onClick={()=>setActive("ecosystem")} className="px-4 py-2.5 rounded-xl bg-white text-black text-sm font-semibold flex items-center gap-2">Ver ecossistema <ChevronRight size={16}/></button><button onClick={()=>setActive("products")} className="px-4 py-2.5 rounded-xl border border-white/10 text-sm">Gerir produtos</button></div></div></section>
          <section className="grid sm:grid-cols-2 xl:grid-cols-4 gap-4 mt-6">{[["Produtos","4","Boxes"],["Ativos","1","Activity"],["Planeados","3","GitBranch"],["Saúde","100%","ShieldCheck"]].map(([a,b,c])=>{const I=c==="Boxes"?Boxes:c==="Activity"?Activity:c==="GitBranch"?GitBranch:ShieldCheck;return <div key={a} className="glass rounded-2xl p-5"><I size={18} className="text-zinc-500"/><div className="mt-5 text-2xl font-semibold">{b}</div><div className="text-xs text-zinc-500 mt-1">{a}</div></div>})}</section>
          <div className="mt-8 flex items-center justify-between"><div><h3 className="font-semibold">Aplicações</h3><p className="text-xs text-zinc-500 mt-1">Os produtos que formam o ecossistema.</p></div><button onClick={()=>setActive("products")} className="text-xs text-zinc-400 hover:text-white flex gap-1 items-center">Ver todos <ArrowUpRight size={14}/></button></div>
          <ProductGrid onOpen={setWindowProduct}/>
        </>}

        {active==="products" && <><SectionTitle title="Produtos" text="Cada produto vive de forma independente, mas pertence ao mesmo ecossistema."/><ProductGrid onOpen={setWindowProduct}/><div className="mt-6 border border-dashed border-white/10 rounded-2xl p-8 text-center"><Plus className="mx-auto text-zinc-600"/><div className="mt-3 font-medium">Adicionar novo produto</div><p className="text-xs text-zinc-600 mt-1">Em breve, diretamente pelo painel.</p></div></>}

        {active==="ecosystem" && <><SectionTitle title="Mapa do ecossistema" text="A arquitetura visual da tua empresa, começando pelo Finance Flow AI."/><div className="glass rounded-3xl p-8 lg:p-12 min-h-[550px] flex flex-col items-center justify-center overflow-hidden"><div className="relative"><div className="absolute left-1/2 top-full w-px h-20 bg-gradient-to-b from-white/30 to-transparent"/><div className="rounded-2xl border border-white/15 bg-white text-black px-8 py-5 shadow-2xl text-center"><div className="text-[10px] uppercase tracking-[.2em] text-zinc-500">Root</div><div className="text-xl font-bold">ECOSYSTEM OS</div></div></div><div className="h-20 w-[75%] border-t border-x border-white/10 mt-20 rounded-t-3xl"/><div className="grid grid-cols-2 lg:grid-cols-4 gap-4 w-full max-w-5xl">{products.map(p=>{const I=p.icon;return <button onClick={()=>p.status==="active"&&setWindowProduct(p)} key={p.id} className="glass rounded-2xl p-5 text-left hover:border-white/20 transition"><div className="flex items-center justify-between"><I size={20}/><span className={`text-[10px] px-2 py-1 rounded-full ${p.status==="active"?"bg-emerald-400/10 text-emerald-300":"bg-white/5 text-zinc-500"}`}>{p.status==="active"?"ATIVO":"FUTURO"}</span></div><div className="mt-5 font-semibold">{p.name}</div><div className="text-xs text-zinc-600 mt-1">{p.category}</div></button>})}</div></div></>}

        {active==="activity" && <><SectionTitle title="Atividade" text="Linha de atividade global do ecossistema."/><div className="glass rounded-2xl divide-y divide-white/5"><ActivityRow icon={<Package size={17}/>} title="Finance Flow AI" text="Produto registado como primeiro ramo do ecossistema." time="Agora"/><ActivityRow icon={<Network size={17}/>} title="Ecosystem OS" text="Workspace criado e inicializado." time="Agora"/><ActivityRow icon={<ShieldCheck size={17}/>} title="Arquitetura" text="Camada central preparada para futuras integrações." time="Hoje"/></div></>}
        {active==="settings" && <><SectionTitle title="Definições" text="Configurações globais do Ecosystem OS."/><div className="glass rounded-2xl p-6 space-y-5"><Setting title="Workspace" value="Admin workspace"/><Setting title="Ambiente" value="Production ready"/><Setting title="Produtos conectados" value="1 / 4"/><Setting title="Autenticação central" value="Preparada para implementação"/></div></>}
      </div>
    </main>

    {windowProduct && <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-md flex items-center justify-center p-5" onClick={()=>setWindowProduct(null)}><div className="w-full max-w-3xl glass rounded-3xl overflow-hidden shadow-2xl" onClick={e=>e.stopPropagation()}><div className="p-5 border-b border-white/5 flex items-center justify-between"><div className="flex items-center gap-3"><windowProduct.icon size={21}/><div><div className="font-semibold">{windowProduct.name}</div><div className="text-xs text-zinc-500">{windowProduct.category}</div></div></div><button onClick={()=>setWindowProduct(null)}><X size={19}/></button></div><div className="p-8 min-h-72 flex flex-col justify-center"><div className="text-xs uppercase tracking-[.2em] text-zinc-600">Application window</div><h2 className="text-3xl font-semibold mt-2">{windowProduct.name}</h2><p className="text-zinc-400 mt-3 max-w-xl">{windowProduct.description}</p>{windowProduct.status==="active"?<a href={windowProduct.url} target="_blank" rel="noreferrer" className="mt-7 w-fit px-4 py-2.5 rounded-xl bg-white text-black text-sm font-semibold flex items-center gap-2">Abrir aplicação <ExternalLink size={15}/></a>:<div className="mt-7 text-xs text-zinc-600">Este produto está reservado para uma próxima fase.</div>}</div></div></div>}
  </div>
}

function ProductGrid({onOpen}:{onOpen:(p:typeof products[number])=>void}){return <div className="grid md:grid-cols-2 xl:grid-cols-4 gap-4 mt-5">{products.map(p=>{const I=p.icon;return <button key={p.id} onClick={()=>onOpen(p)} className={`glass rounded-2xl p-5 text-left bg-gradient-to-br ${p.accent} hover:-translate-y-0.5 hover:border-white/15 transition`}><div className="flex items-start justify-between"><div className="w-10 h-10 rounded-xl bg-black/30 border border-white/10 flex items-center justify-center"><I size={19}/></div><span className={`text-[10px] px-2 py-1 rounded-full ${p.status==="active"?"bg-emerald-400/10 text-emerald-300":"bg-white/5 text-zinc-600"}`}>{p.status==="active"?"ATIVO":"EM BREVE"}</span></div><div className="mt-5 font-semibold">{p.name}</div><div className="text-xs text-zinc-500 mt-1">{p.category}</div><p className="text-xs text-zinc-600 mt-3 leading-5">{p.description}</p><div className="mt-5 pt-4 border-t border-white/5 text-[11px] text-zinc-500 flex items-center justify-between"><span>{p.metric}</span><ArrowUpRight size={14}/></div></button>})}</div>}
function SectionTitle({title,text}:{title:string,text:string}){return <div className="mb-6"><h2 className="text-2xl font-semibold">{title}</h2><p className="text-sm text-zinc-500 mt-1">{text}</p></div>}
function ActivityRow({icon,title,text,time}:{icon:React.ReactNode,title:string,text:string,time:string}){return <div className="p-5 flex gap-4"><div className="w-9 h-9 rounded-xl bg-white/5 flex items-center justify-center text-zinc-400">{icon}</div><div className="flex-1"><div className="text-sm font-medium">{title}</div><div className="text-xs text-zinc-500 mt-1">{text}</div></div><div className="text-[11px] text-zinc-600">{time}</div></div>}
function Setting({title,value}:{title:string,value:string}){return <div className="flex items-center justify-between border-b border-white/5 pb-4"><div className="text-sm">{title}</div><div className="text-xs text-zinc-500">{value}</div></div>}
